from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa
revision='20260715_0002'; down_revision='20260714_0001'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('tasks',sa.Column('id',sa.String(64),primary_key=True),sa.Column('workspace_id',sa.String(64),nullable=True),sa.Column('task_type',sa.String(32),nullable=False),sa.Column('priority',sa.String(32),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('result_json',sa.JSON(),nullable=True),sa.Column('creator',sa.String(255)),sa.Column('executor',sa.String(255)),sa.Column('retry_count',sa.Integer(),nullable=False),sa.Column('max_retries',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('finished_at',sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(['workspace_id'],['workspaces.id'],ondelete='SET NULL'))
    for n,c in [('workspace_id','workspace_id'),('task_type','task_type'),('priority','priority'),('status','status')]: op.create_index(f'ix_tasks_{n}','tasks',[c])
    op.create_table('task_runs',sa.Column('id',sa.String(64),primary_key=True),sa.Column('task_id',sa.String(64),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('attempt',sa.Integer(),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('finished_at',sa.DateTime(timezone=True)),sa.Column('duration_ms',sa.Float()),sa.Column('error',sa.Text()),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(['task_id'],['tasks.id'],ondelete='CASCADE')); op.create_index('ix_task_runs_task_id','task_runs',['task_id'])
    op.create_table('task_logs',sa.Column('id',sa.String(64),primary_key=True),sa.Column('task_id',sa.String(64),nullable=False),sa.Column('run_id',sa.String(64)),sa.Column('level',sa.String(16),nullable=False),sa.Column('message',sa.Text(),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(['task_id'],['tasks.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['run_id'],['task_runs.id'],ondelete='SET NULL')); op.create_index('ix_task_logs_task_id','task_logs',['task_id']); op.create_index('ix_task_logs_run_id','task_logs',['run_id'])
    op.create_table('task_artifacts',sa.Column('id',sa.String(64),primary_key=True),sa.Column('task_id',sa.String(64),nullable=False),sa.Column('run_id',sa.String(64)),sa.Column('artifact_type',sa.String(64),nullable=False),sa.Column('name',sa.String(255),nullable=False),sa.Column('path',sa.Text(),nullable=False),sa.Column('mime_type',sa.String(255)),sa.Column('size_bytes',sa.Integer()),sa.Column('checksum',sa.String(128)),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(['task_id'],['tasks.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['run_id'],['task_runs.id'],ondelete='SET NULL')); op.create_index('ix_task_artifacts_task_id','task_artifacts',['task_id']); op.create_index('ix_task_artifacts_run_id','task_artifacts',['run_id'])
def downgrade():
    op.drop_table('task_artifacts'); op.drop_table('task_logs'); op.drop_table('task_runs'); op.drop_table('tasks')
