"""P3-001.3b Extraction Persistence and API.

Revision ID: 20260805_0055
Revises: 20260804_0054
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260805_0055"
down_revision = "20260804_0054"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "document_extraction_runs",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "workspace_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "parser",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "parser_version",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "source_sha256",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "extracted_text_sha256",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "total_characters",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "unit_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "chunk_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "warnings_json",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "error_code",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sa.String(length=2000),
            nullable=True,
        ),
        sa.Column(
            "error_details_json",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "requested_by",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "attempt_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "failed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN "
            "('pending', 'running', 'completed', 'failed')",
            name="ck_document_extraction_runs_status",
        ),
        sa.CheckConstraint(
            "total_characters >= 0",
            name=(
                "ck_document_extraction_runs_"
                "total_characters"
            ),
        ),
        sa.CheckConstraint(
            "unit_count >= 0",
            name=(
                "ck_document_extraction_runs_unit_count"
            ),
        ),
        sa.CheckConstraint(
            "chunk_count >= 0",
            name=(
                "ck_document_extraction_runs_chunk_count"
            ),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=(
                "ck_document_extraction_runs_attempt_count"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "source_sha256",
            "parser_version",
            name=(
                "uq_document_extraction_runs_exact"
            ),
        ),
    )
    for name in (
        "document_id",
        "workspace_id",
        "status",
        "parser_version",
        "source_sha256",
        "requested_by",
        "created_at",
    ):
        op.create_index(
            f"ix_document_extraction_runs_{name}",
            "document_extraction_runs",
            [name],
        )

    op.create_table(
        "document_extraction_units",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "run_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "workspace_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "text_sha256",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "character_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "provenance_json",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=(
                "ck_document_extraction_units_ordinal"
            ),
        ),
        sa.CheckConstraint(
            "character_count >= 0",
            name=(
                "ck_document_extraction_units_"
                "character_count"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["document_extraction_runs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "ordinal",
            name=(
                "uq_document_extraction_units_ordinal"
            ),
        ),
    )
    for name in (
        "run_id",
        "document_id",
        "workspace_id",
        "kind",
        "text_sha256",
    ):
        op.create_index(
            f"ix_document_extraction_units_{name}",
            "document_extraction_units",
            [name],
        )

    op.create_table(
        "document_extraction_chunks",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "run_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "workspace_id",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "text_sha256",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "character_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "character_start",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "character_end",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "source_unit_ordinals_json",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "provenance_json",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=(
                "ck_document_extraction_chunks_ordinal"
            ),
        ),
        sa.CheckConstraint(
            "character_count >= 0",
            name=(
                "ck_document_extraction_chunks_"
                "character_count"
            ),
        ),
        sa.CheckConstraint(
            "character_start >= 0",
            name=(
                "ck_document_extraction_chunks_"
                "character_start"
            ),
        ),
        sa.CheckConstraint(
            "character_end >= character_start",
            name=(
                "ck_document_extraction_chunks_range"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["document_extraction_runs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "ordinal",
            name=(
                "uq_document_extraction_chunks_ordinal"
            ),
        ),
    )
    for name in (
        "run_id",
        "document_id",
        "workspace_id",
        "text_sha256",
    ):
        op.create_index(
            f"ix_document_extraction_chunks_{name}",
            "document_extraction_chunks",
            [name],
        )


def downgrade() -> None:
    op.drop_table("document_extraction_chunks")
    op.drop_table("document_extraction_units")
    op.drop_table("document_extraction_runs")
